# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f69384da0998a21e201cb3c25da2bbd22b22647d39296a1a7669a8c5a74ce44886e45f49aaa4b76527621d70546538f0f6cc8f28c654e0cb7cadf3c1780b0f28

test:
  secret_key_base: bd7f86057ea90f076509dcf9d86dbed93314abff02dc76afda43ec2b831fb3aacd5ecc2a38640d806038f7244ed2ff731944087bc8559067b2f4147573845239

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
